<a href="https://colab.research.google.com/github/CarlosMassarelli/CarlosMassarelli/blob/main/Numpy_iniciando.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
km = np.loadtxt("carros-km.txt")

In [ ]:
km

In [ ]:
anos = np.loadtxt("carros-anos.txt", dtype = int)

In [ ]:
anos


In [ ]:
km_med= km/(2019-anos)

<ipython-input-8-03fddb95f046>:1: RuntimeWarning: invalid value encountered in true_divide
  km_med= km/(2019-anos)


In [ ]:
km_med

In [ ]:
type(km_med)

numpy.ndarray

In [ ]:
2*3

6

In [ ]:
10/3

3.3333333333333335

In [ ]:
10//3 #somente inteiro da divisão

3

In [ ]:
10%3 #somente resto da divisão

1

In [ ]:
2**3

8

In [ ]:
ano_atual = 2019
ano_fabricacao = 2003
km_total = 44410.0

In [ ]:
km_media = km_total / (ano_atual - ano_fabricacao)
km_media


2775.625

In [ ]:
ano_atual = 2019
ano_fabricacao = 2003
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)

km_total += km_media

In [ ]:
km_total

47185.625

In [ ]:
#tipos de variáveis e strings

In [ ]:
type(km_total)

float

In [ ]:
nome='Jetta Variant'
nome

'Jetta Variant'

In [ ]:
nome="'Jetta Variant'"
nome

"'Jetta Variant'"

In [ ]:
#criando uma string com linhas 
carro='''
  Nome
  Idade
  Nota
'''
carro

'\n  Nome\n  Idade\n  Nota\n'

In [ ]:
type(carro)

str

In [ ]:
#transformações de dados

In [ ]:
a=10
b=20
c='Python é '
d='legal'
type (a)


int

In [ ]:
type (b)


int

In [ ]:
type (c)


str

In [ ]:
type (d)

str

In [ ]:
str (a)

'10'

In [ ]:
str (b)

'20'

In [ ]:
c+d

'Python élegal'

In [ ]:
c+str(a)

'Python é 10'

In [ ]:
c+d+str(b)

'Python é legal20'

In [ ]:
#identação é obrigatório...

In [ ]:
ano_atual = 2019
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
  print ('Verdadeiro')
else:
  print ('falso')

Verdadeiro


In [ ]:
'''isto é um 
comentário logo'''

In [ ]:
#formatação de strings

In [ ]:
print('Olá, {}!'.format('Rodrigo'))

Olá, Rodrigo!


In [ ]:
print('Olá, {}! Este é o seu acesso de número {}'.format('Rodrigo', 32))

Olá, Rodrigo! Este é o seu acesso de número 32


In [ ]:
print('Olá, {nome}! Este é o seu acesso de número {acessos}'.format(nome='Rodrigo', acessos=32))

Olá, Rodrigo! Este é o seu acesso de número 32


In [ ]:
#formatação de strings novo

In [ ]:
mome = 'Rodrigo'
acessos = 32
print(f'Olá, {nome}! Este é o seu acesso de número {acessos}')

Olá, Jetta Variant! Este é o seu acesso de número 32


In [ ]:
#coleção de listas

In [ ]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [ ]:
Carro_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [ ]:
Carros = [Carro_1, Carro_2]


In [ ]:
Carros


[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [ ]:
'Jetta Variant' in Carros

False

In [ ]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']


In [ ]:
'Rodas de liga' in Acessorios

True

In [ ]:
'Rodas de liga' not in Acessorios

False

In [ ]:
carro = [
    'Jetta Variant', 
    'Motor 4.0 Turbo', 
    2003, 
    44410.0, 
    False, 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 
    88078.64
]

In [ ]:
'2003' in carro

False

In [ ]:
'False' not in carro

True

In [ ]:
'Rodas de liga' in carro

False

In [ ]:
Acessorios[0]

'Rodas de liga'

In [ ]:
Carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [ ]:
Carros[0][1]

'Motor 4.0 Turbo'

In [ ]:
Carros[1:2]

[['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [ ]:
Acessorios.sort()

In [ ]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

**Estruturas de Repetição**

In [ ]:
for item in Acessorios:
  print(item)

Ar condicionado
Bancos de couro
Piloto automático
Rodas de liga
Sensor crepuscular
Sensor de chuva
Sensor de estacionamento
Travas elétricas


In [ ]:
range (10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for i in range(10):
  print (i ** 2)

0
1
4
9
16
25
36
49
64
81


In [ ]:
quadrado = []
for i in range(10):
  quadrado.append (i**2)
quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
[t**2 for t in range (10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [ ]:
for lista in dados: #percorre a lista
    print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [ ]:
for lista in dados:
  for item in lista:
    print (item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [ ]:
Acessorios = []
for lista in dados:
  for item in lista:
        Acessorios.append(item) #cria uma lista única
print(Acessorios) #lista completa e conjunta

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva', 'Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento', 'Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [ ]:
list(set(Acessorios)) #listando a lista sem repetições

['Painel digital',
 'Travas elétricas',
 'Piloto automático',
 'Freios ABS',
 '4 X 4',
 'Teto panorâmico',
 'Rodas de liga',
 'Bancos de couro',
 'Central multimídia',
 'Câmbio automático',
 'Câmera de estacionamento',
 'Ar condicionado',
 'Sensor de chuva',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Vidros elétricos',
 'Sensor de estacionamento']

In [ ]:
list(set([item for lista in dados for item in lista]))

['Painel digital',
 'Travas elétricas',
 'Piloto automático',
 'Freios ABS',
 '4 X 4',
 'Teto panorâmico',
 'Rodas de liga',
 'Bancos de couro',
 'Central multimídia',
 'Câmbio automático',
 'Câmera de estacionamento',
 'Ar condicionado',
 'Sensor de chuva',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Vidros elétricos',
 'Sensor de estacionamento']

In [ ]:
dados = [ 
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
]

In [ ]:
result_2 = []
for lista in dados:
    result_2 += lista
result_2

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

Instrução IF

In [ ]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
zero_km_Y = []

for lista in dados:
  if(lista[2]==True):
    zero_km_Y.append(lista)

zero_km_Y

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
zero_km_N = []

for lista in dados:
  if(lista[2]==False):
    zero_km_N.append(lista)

zero_km_N

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
[lista for lista in dados if lista[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
zero_km_Y, zero_km_Y = [], []

for lista in dados:
  if(lista[2]==True):
    zero_km_Y.append(lista)
  else:
    zero_km_N.append(lista)


In [ ]:
zero_km_Y

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
zero_km_N

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False],
 ['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
A, B, C = [],[],[]

for lista in dados:
  if (lista[1] <=2000):
    A.append(lista)
  elif(lista[1]>2000 and lista[1]<=2010): #pode 2000 < lista[1] <= 2010
    B.append(lista)
  else:
    C.append(lista)

In [ ]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [ ]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [ ]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
import numpy as np


In [ ]:
km = np.loadtxt(fname='carros-km.txt', dtype = int)

In [ ]:
km


array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [ ]:
np.dtype

numpy.dtype

In [ ]:
Acessorios = np.array(dados)

In [ ]:
Acessorios

array([['Jetta Variant', '2003', 'False'],
       ['Passat', '1991', 'False'],
       ['Crossfox', '1990', 'False'],
       ['DS5', '2019', 'True'],
       ['Aston Martin DB4', '2006', 'False'],
       ['Palio Weekend', '2012', 'False'],
       ['A5', '2019', 'True'],
       ['Série 3 Cabrio', '2009', 'False'],
       ['Dodge Jorney', '2019', 'False'],
       ['Carens', '2011', 'False']], dtype='<U21')

In [ ]:
km.shape

(258,)

In [ ]:
Acessorios.shape

(10, 3)

In [ ]:
np_array = np.arange(1000000) #com numpy

In [ ]:
py_list = list(range(1000000)) #com python

In [ ]:
%time for _ in range(100): np_array *= 2 #temporizando a execução(performance)

CPU times: user 61.9 ms, sys: 0 ns, total: 61.9 ms
Wall time: 67 ms


In [ ]:
%time for _ in range(100): py_list = [x * 2 for x in py_list] #temporizando a execução(performance)

CPU times: user 9.43 s, sys: 2.95 s, total: 12.4 s
Wall time: 12.5 s


**Operações aritméticas com arrays Numpy**

In [ ]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
# idade = 2019 - anos

In [ ]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [ ]:
idade = 2019 - anos

In [ ]:
idade

array([16, 28, 29,  0, 13])

In [ ]:
km_media = km/idade

<ipython-input-9-6e6c1cda6d70>:1: RuntimeWarning: invalid value encountered in true_divide
  km_media = km/idade


In [ ]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [ ]:
dados = np.array([km, anos])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados.shape

(2, 5)

In [ ]:
dados [0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [ ]:
km_media = dados[0] / (2019 - dados[1])
km_media

<ipython-input-17-dac51efab2ed>:1: RuntimeWarning: invalid value encountered in true_divide
  km_media = dados[0] / (2019 - dados[1])


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [ ]:
dados [0,0]

44410.0

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
item = 6
index = item-1
contador[index]

5

In [ ]:
contador [1:4]

array([1, 2, 3])

In [ ]:
contador[1:8:2]

array([1, 3, 5, 7])

In [ ]:
contador [::2]

array([0, 2, 4, 6, 8])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[:,1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [ ]:
dados[:,1:3][0] / (2019 - dados[:,1:3][1])

array([ 204.        , 1280.10344828])

In [ ]:
dados[:, dados[1]>2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [ ]:
dados.shape

(2, 5)

In [ ]:
dados.ndim

2

In [ ]:
dados.size

10

In [ ]:
dados.dtype

dtype('float64')

In [ ]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [ ]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [ ]:
contador.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape((5,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape((5,2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [ ]:
np.array(info_carros).reshape((2,5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [ ]:
np.array(info_carros).reshape((5,2), order = 'F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

In [ ]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados_new.resize((3,5))

ValueError: ignored

In [ ]:
dados_new.resize((3,5), refcheck=False)

In [ ]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [ ]:
dados_new[2]=dados_new[0] / (2019 - dados_new[1])
dados_new

<ipython-input-53-7d8d1e8bf5f4>:1: RuntimeWarning: invalid value encountered in true_divide
  dados_new[2]=dados_new[0] / (2019 - dados_new[1])


array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

In [ ]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [ ]:
anos.shape

(258,)

In [ ]:
dataset = np.column_stack ((anos, km, valor))

In [ ]:
dataset

In [ ]:
dataset.shape

(258, 3)

In [ ]:
np.mean(dataset, axis = 0) #média por coluna...

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset[:,1]) #retorna a média da kilometragem

44499.41472868217

In [ ]:
!python -V

Python 3.9.16


**Pandas em Python**


In [ ]:
import pandas as pd

In [ ]:
dataset = pd.read_csv('db.csv', sep = ';')
pd.set_option('display.max_rows', 10) #para ver mais linhas
pd.set_option('display.max_columns', 10) #para ver mais colunas
dataset

Nome                  Motor   Ano  Quilometragem  \
0            Jetta Variant        Motor 4.0 Turbo  2003        44410.0   
1                   Passat           Motor Diesel  1991         5712.0   
2                 Crossfox        Motor Diesel V8  1990        37123.0   
3                      DS5        Motor 2.4 Turbo  2019            NaN   
4         Aston Martin DB4        Motor 2.4 Turbo  2006        25757.0   
..                     ...                    ...   ...            ...   
253           Phantom 2013               Motor V8  2014        27505.0   
254  Cadillac Ciel concept               Motor V8  1991        29981.0   
255             Classe GLK  Motor 5.0 V8 Bi-Turbo  2002        52637.0   
256       Aston Martin DB5           Motor Diesel  1996         7685.0   
257                  Macan        Motor Diesel V6  1992        50188.0   

     Zero_km                                         Acessórios      Valor  
0      False  ['Rodas de liga', 'Travas elétricas', 'Piloto ...   88078.64  
1      False  ['Central multimídia', 'Teto panorâmico', 'Fre...  106161.94  
2      False  ['Piloto automático', 'Controle de estabilidad...   72832.16  
3       True  ['Travas elétricas', '4 X 4', 'Vidros elétrico...  124549.07  
4      False  ['Rodas de liga', '4 X 4', 'Central multimídia...   92612.10  
..       ...                                                ...        ...  
253    False  ['Controle de estabilidade', 'Piloto automátic...   51759.58  
254    False  ['Bancos de couro', 'Painel digital', 'Sensor ...   51667.06  
255    False  ['Rodas de liga', 'Controle de tração', 'Câmbi...   68934.03  
256    False  ['Ar condicionado', '4 X 4', 'Câmbio automátic...  122110.90  
257    False  ['Central multimídia', 'Teto panorâmico', 'Vid...   90381.47  

[258 rows x 7 columns]

In [ ]:
type (dataset)
dataset.dtypes


Nome              object
Motor             object
Ano                int64
Quilometragem    float64
Zero_km             bool
Acessórios        object
Valor            float64
dtype: object

In [ ]:
dataset[['Quilometragem', 'Valor']].describe()

Quilometragem          Valor
count     197.000000     258.000000
mean    58278.421320   98960.513101
std     35836.733259   29811.932305
min       107.000000   50742.100000
25%     27505.000000   70743.512500
50%     55083.000000   97724.380000
75%     90495.000000  124633.302500
max    119945.000000  149489.920000

In [ ]:
dataset.info

<bound method DataFrame.info of                       Nome                  Motor   Ano  Quilometragem  \
0            Jetta Variant        Motor 4.0 Turbo  2003        44410.0   
1                   Passat           Motor Diesel  1991         5712.0   
2                 Crossfox        Motor Diesel V8  1990        37123.0   
3                      DS5        Motor 2.4 Turbo  2019            NaN   
4         Aston Martin DB4        Motor 2.4 Turbo  2006        25757.0   
..                     ...                    ...   ...            ...   
253           Phantom 2013               Motor V8  2014        27505.0   
254  Cadillac Ciel concept               Motor V8  1991        29981.0   
255             Classe GLK  Motor 5.0 V8 Bi-Turbo  2002        52637.0   
256       Aston Martin DB5           Motor Diesel  1996         7685.0   
257                  Macan        Motor Diesel V6  1992        50188.0   

     Zero_km                                         Acessórios      Valor  
0 

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Nome           258 non-null    object 
 1   Motor          258 non-null    object 
 2   Ano            258 non-null    int64  
 3   Quilometragem  197 non-null    float64
 4   Zero_km        258 non-null    bool   
 5   Acessórios     258 non-null    object 
 6   Valor          258 non-null    float64
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 12.5+ KB


Tuplas... imutáveis...

In [ ]:
()

()

In [ ]:
1,2,3

(1, 2, 3)

In [ ]:
nome='passat'
valor=15000
(nome, valor)

('passat', 15000)

In [ ]:
nomes_carros = tuple(['Jetta Variant', 'Passat', 'Crossfox', 'DS5'])
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5')

In [ ]:
type(nomes_carros)

tuple

In [ ]:
nomes_carros[-1]

'DS5'

In [ ]:
nomes_carros[1:3]

('Passat', 'Crossfox')

In [ ]:
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DS5', ('Fusca', 'Gol', 'C4'))
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5', ('Fusca', 'Gol', 'C4'))

In [ ]:
nomes_carros[4][2]

'C4'

In [ ]:
carros = (
    (
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ('Rodas de liga', 'Travas elétricas', 'Piloto automático')
    ),
    (
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ('Central multimídia', 'Teto panorâmico', 'Freios ABS')
    )
)

In [ ]:
carros[0][3]

False

In [ ]:
carros[-1][-1][-1]

'Freios ABS'

In [ ]:
carros[0][-1][:2]

('Rodas de liga', 'Travas elétricas')

In [ ]:
for item in nomes_carros:
  print(item)

Jetta Variant
Passat
Crossfox
DS5
('Fusca', 'Gol', 'C4')


In [ ]:
carro_1, carro_2, carro_3, carro_4, carros_5 = nomes_carros

In [ ]:
carro_2

'Passat'

In [ ]:
_, A, _, B, _=nomes_carros

In [ ]:
A

'Passat'

In [ ]:
_, A, *_=nomes_carros

In [ ]:
A

'Passat'

In [ ]:
carros = ['Jetta Variant', 'Passat', 'Crossfox', 'DS5']
carros

['Jetta Variant', 'Passat', 'Crossfox', 'DS5']

In [ ]:
valores = [88078.64, 106161.94, 72832.16, 124549.07]
valores

[88078.64, 106161.94, 72832.16, 124549.07]

In [ ]:
zip(carros, valores)

In [ ]:
list(zip(carros, valores))

[('Jetta Variant', 88078.64),
 ('Passat', 106161.94),
 ('Crossfox', 72832.16),
 ('DS5', 124549.07)]

In [ ]:
for item in zip(carros, valores):
  print (item)

('Jetta Variant', 88078.64)
('Passat', 106161.94)
('Crossfox', 72832.16)
('DS5', 124549.07)


In [ ]:
for carro, valor in zip(carros, valores):
  print (carro, valor)

Jetta Variant 88078.64
Passat 106161.94
Crossfox 72832.16
DS5 124549.07


In [ ]:
for carro, valor in zip(carros, valores):
  if (valor>100000):
    print(carro)


Passat
DS5


In [ ]:
dados = {'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}
dados

{'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}

In [ ]:
dados ['Passat']

106161.94

In [ ]:
'Passat' in dados

True

In [ ]:
'Passat' not in dados

False

In [ ]:
len (dados)

3

In [ ]:
dados.update({'Passat': 106161.95, 'Fusca': 150000})

In [ ]:
dados

{'Jetta Variant': 88078.64,
 'Passat': 106161.95,
 'Crossfox': 72832.16,
 'Fusca': 150000}

In [ ]:
dadosCopy = dados.copy()

In [ ]:
dados.keys()

dict_keys(['Jetta Variant', 'Passat', 'Crossfox', 'Fusca'])

In [ ]:
for key in dados.keys():
  print (dados[key])

88078.64
106161.95
72832.16
150000


In [ ]:
dados

{'Jetta Variant': 88078.64,
 'Passat': 106161.95,
 'Crossfox': 72832.16,
 'Fusca': 150000}

In [ ]:
sum(dados.values())

417072.75

In [ ]:
sum?
